/**
 * Autogenerated by Dubbo Compiler (0.1.0)
 *
 * Thrift (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
public interface ClassNameTestDubbo {

  public String echo(String arg);

}
